### ISSUE TITLE
Theme not working with the latest documentationjs code

### ISSUE THREAD

**Issue by jainanshul** [documentationjs/documentation-theme-light#3]
I get the following error when using this theme with the latest documentationjs code.

```
docs/node_modules/documentation/lib/commands/build.js:60
      throw err;
      ^

TypeError: theme is not a function
    at Object.makeHTML [as html] (docs/node_modules/documentation/lib/output/html.js:21:3)
    at onDocumented (docs/node_modules/documentation/lib/commands/build.js:63:47)
    at docs/node_modules/documentation/index.js:101:7
    at docs/node_modules/documentation/lib/input/dependency.js:45:5
    at ConcatStream.<anonymous> (docs/node_modules/documentation/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (docs/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (docs/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (docs/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
```

**Comment by jtorresfabra** [comment]
The error seems to be in https://github.com/documentationjs/documentation-theme-light/blob/master/index.js#L1 as it cannot be void, it needs to be a function with these signature:

module.exports = function (comments, options, callback) {
}

**Comment by pronebird** [comment]
@jtorresfabra does not work with `module.exports = function (comments, options, callback) {}` either.

**Comment by ur300** [comment]
here is the fixed version https://github.com/ur300/documentation-theme-light
